tables:
  table0:
    id: 0
    person_count: -1
    status: "unknown"
    order: []
    location:
      position: { x: 6.783693856, y: 0.174163159293, z: 0.0 }
      orientation: { x: 0.0, y: 0.0, z: 0.694576864659, w: 0.719418500652 }
    cuboid:
      frame: 'map'
      max_xyz: [ 8.042, 2.315, 10.0 ]
      min_xyz: [ 5.587, 0.480, 0.00 ]
    lookLR: [[6.17, 1.66], [7.29, 1.66]]

  table1:
    id: 1
    person_count: -1
    status: "unknown"
    order: []
    location:
      position: { x: 9.38863755014, y: 0.202148583446, z: 0.0 }
      orientation: { x: 0.0, y: 0.0, z: 0.655514163585, w: 0.7551828794 }
    cuboid:
      frame: 'map'
      max_xyz: [ 10.771, 2.283, 10.0 ]
      min_xyz: [ 8.057, 0.574, 0.000 ]
    lookLR: [[8.93, 1.54], [9.97, 1.66]]

Bar:
  location:
    position: { x: 0.447394763282, y: 0.00754231950464, z: 0.0 }
    orientation: { x: 0.0, y: 0.0, z: -0.663126835597, w: 0.748507047336 }

Home:
  location:
    position: { x: 0, y: 0, z: 0.0 }
    orientation: { x: 0.0, y: 0.0, z: 0, w: 1 }
