tables:
  # table0:
  #   id: 0
  #   person_count: -1
  #   status: "Unknown"
  #   order: []
  #   location:
  #     position: { x: 21.9364580226, y: 19.5228118361, z: 0.0 }
  #     orientation: { x: 0.0, y: 0.0, z: -0.356255293448, w: 0.934388658905 }
  #   cuboid:
  #     frame: 'map'
  #     max_xyz: [ 23.348, 20.037, 2.0 ]
  #     min_xyz: [ 22.894, 17.868, 0.2 ]

  # table1:
  #   id: 1
  #   person_count: -1
  #   status: "Unknown"
  #   order: []
  #   location:
  #     position: { x: 20.2735464103, y: 18.3279660725, z: 0.0 }
  #     orientation: { x: 0.0, y: 0.0, z: -0.413929405535, w: 0.910308984485 }
  #   cuboid:
  #     frame: 'map'
  #     max_xyz: [ 21.946, 18.803, 2.0 ]
  #     min_xyz: [ 20.975, 16.347, 0.2 ]

  # table2:
  #   id: 2
  #   person_count: -1
  #   status: "Unknown"
  #   order: []
  #   location:
  #     position: { x: 18.7223304879, y: 16.3367719378, z: 0.0 }
  #     orientation: { x: 0.0, y: 0.0, z: -0.347106215937, w: 0.937825823305 }
  #   cuboid:
  #     frame: 'map'
  #     max_xyz: [ 20.233, 16.875, 2.0 ]
  #     min_xyz: [ 19.335, 14.406, 0.2 ]
  
  table3:
    id: 3
    person_count: -1
    status: "Unknown"
    order: []
    location:
      position: { x: 7.03416643896, y: 6.08865910191, z: 0.0 }
      orientation: { x: 0.0, y: 0.0, z: -0.34457305185, w: 0.938759506976 }
    cuboid:
      frame: 'map'
      max_xyz: [ 8.538, 6.454, 5.0 ]
      min_xyz: [ 7.679, 3.495, 0.2 ]
    lookLR: [ [8.648, 5.203], [7.814, 4.383] ]

  table4:
    id: 4
    person_count: -1
    status: "Unknown"
    order: []
    location:
      position: { x: 5.33803681296, y: 4.4170952369, z: 0.0 }
      orientation: { x: 0.0, y: 0.0, z: -0.398052256046, w: 0.917362742571 }
    cuboid:
      frame: 'map'
      max_xyz: [ 6.696, 4.726, 2.0 ]
      min_xyz: [ 5.891, 2.082, 0.2 ]
    lookLR: [ [6.799, 3.513], [6.096, 2.797] ]

  table5:
    id: 5
    person_count: -1
    status: "Unknown"
    order: []
    location:
      position: { x: 3.35535288015, y: 2.39627467118, z: 0.0 }
      orientation: { x: 0.0, y: 0.0, z: -0.350030969818, w: 0.93673812785 }
    cuboid:
      frame: 'map'
      max_xyz: [ 4.830, 2.7110, 2.0 ]
      min_xyz: [ 3.886, -0.198, 0.2 ]
    lookLR: [ [4.824, 1.362], [4.220, 0.619] ]

Bar:
  location:
    position: { x: 9.90713465504, y: 8.17895241188, z: 0.0 }
    orientation: { x: 0.0, y: 0.0, z: 0.934551413362, w: 0.355828126746 }


Home:
  location:
    position: { x: 9.90713465504, y: 8.17895241188, z: 0.0 }
    orientation: { x: 0.0, y: 0.0, z: 0.934551413362, w: 0.355828126746 }
  
WaitingArea:
  location:
    position: { x: 10.261, y: 6.880, z: 0.0 }
    orientation: { x: 0.0, y: 0.0, z: 0.462, w: 0.887 }
  cuboid:
      frame: 'map'
      max_xyz: [ 14.554, 12.128, 0.0 ]
      min_xyz: [ 10.844, 9.545, 0.0 ]

# Proper home: the home above is a fake home
# it is actually the bar
# dont believe in the fake home
# Home:
#   location:
#     position: { x: 12.9419836537, y: 12.3956073234, z: 0.0 }
#     orientation: { x: 0.0, y: 0.0, z: -0.91871896815, w: 0.394911961787 }
