play_motion:
  motions:
    look_down:
      joints: [head_1_joint, head_2_joint]
      points:
      - positions: [0.0, -0.5]
        time_from_start: 2.0
    
    back_to_default:
      joints: [head_1_joint, head_2_joint]
      points:
      - positions: [0.0, 0.0]
        time_from_start: 2.0
